---
title: "directorate_of_fisheries"
author: "jst"
date: "8 janúar 2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readxl)
library(tidyverse)
library(dplyr)

library(rstatix)
library(FSA)

library(conover.test)
library(poweRlaw)


library(ecolTest)

```



```{r}
bot_jul_des <- 
  read_excel("botnvarpa_jul_des_2021.xlsx", 
                          sheet = "5_flokkar")
bot_jul_des_piv <-
  bot_jul_des %>% 
  pivot_longer(c(vika_1, vika_2,vika_3,vika_4,vika_5), 
              names_to = "vika", 
              values_to = "fjoldi") %>% 
  arrange(vika)
   
bot_jul_des_piv<-bot_jul_des_piv %>% 
  drop_na()                 

bot_jul_des_piv %>% 
ggplot( aes(x = reorder(vika,
                        fjoldi,FUN=median), 
                        y = fjoldi, 
                        col = vika)) + 
  geom_boxplot(outlier.shape = NA) + 
  geom_jitter(width = 0.1) + 
  theme(legend.position="middle")+
  coord_flip()



```



```{r}

x1<-  bot_jul_des$vika_1 
new.x1<-x1[!is.na(x1)]

x2<-  bot_jul_des$vika_2
new.x2<-x2[!is.na(x2)]

x3<-  bot_jul_des$vika_3
new.x3<-x3[!is.na(x3)]

x4<-  bot_jul_des$vika_4 
new.x4<-x4[!is.na(x4)]

x5<-  bot_jul_des$vika_5 
new.x5<-x5[!is.na(x5)]


x <-c(new.x1,new.x2,new.x3,new.x4,new.x5)

length(new.x5)

g <- factor(rep(1:5, c(12,15, 14,10,10)),
            labels = c("vika1",
                       "vika2",
                       "vika3",
                       "vika4",
                       "vika5"))


kruskal.test(x,g)

#Conover próf
conover.test(x,g, method = "bh")

#Dunn próf
bot_jul_des_piv%>% 
  drop_na() %>% 
  dunn_test(fjoldi~vika,p.adjust.method = "bonferroni") 

#Wilcox próf
bot_jul_des_piv %>% 
  drop_na() %>% 
  wilcox_test(fjoldi~vika, p.adjust.method = "bonferroni")


```

```{r}
#powerlaw distribution
m_pl = displ$new(bot_jul_des_piv$fjoldi)
est=estimate_xmin(m_pl)
m_pl$setXmin(est)


#log normal distribution
m_ln =dislnorm$new(bot_jul_des_piv$fjoldi)
est=estimate_xmin(m_ln)
m_ln$setXmin(est)

#poisson distribution
m_pois =dispois$new(bot_jul_des_piv$fjoldi)
est=estimate_xmin(m_pois)
m_pois$setXmin(est)


plot(m_pl1)
lines(m_pl, col=2)
lines(m_ln, col=3)
lines(m_pois,col=4)

m_pl1 = displ$new(new.x3)
est=estimate_xmin(m_pl1)
m_pl1$setXmin(est)



bs_p = bootstrap_p(m_pl)

bs_p

plot(bs_p)

```
```{r}
library(diverse)

library(pheatmap)
View(scidat)
scidat

colfunc <- colorRampPalette(c("deepskyblue4", "deepskyblue", "cyan"))


plot_mat <- function(data){
pheatmap(data, colfunc(5), cluster_rows = FALSE, cluster_cols = FALSE)
}

bot_jul_des <- 
  read_excel("botnvarpa_jul_des_2021.xlsx", 
                          sheet = "Sheet1")

hringur <-   read_excel("botnvarpa_jul_des_2021.xlsx", 
                          sheet = "Sheet2")

bot_jul_des <-hringur %>% remove_rownames %>% column_to_rownames(var="names")
bot_jul_des[is.na(bot_jul_des)] <- 0




df2 <- data.matrix(bot_jul_des[,1:5])
rownames(df2) <- rownames(bot_jul_des)

View(df2)
colfunc <- colorRampPalette(c("deepskyblue4", "deepskyblue", "cyan"))


pheatmap(values(tail(df2,20),norm='rac', filter=1),colfunc(10), cluster_rows = FALSE, cluster_cols = FALSE)


ubiquity(data=df2)
round(diversity(data = df2, type = c('hhi', 'gs', 'b','ev')), 3)
round(dis_entities(df2, method = 'cosine'), 2)
variety(df2)

bal <- balance(df2, category_row = TRUE) #note the function balance
barplot(t(bal), legend = FALSE, ylab = "Proportions",
col=c("darkblue","blue","sky blue", "light blue") )




```

```{r}


scale_rows = function(x){
    m = apply(x, 1, mean, na.rm = T)
    s = apply(x, 1, sd, na.rm = T)
    return((x - m) / s)
}

df2 <-apply(df2, MARGIN = 2, FUN = function(X) (X - min(X))/diff(range(X))*2)

View(df2)


Hutcheson_t_test(
  df2[,3],
  df2[,1],
  shannon.base = exp(1),
  alternative = "two.sided",
  difference = 0
)

df2



multiple_Hutcheson_t_test(df2,  shannon.base = 2)


# one-sided test
Hutcheson_t_test(x=polychaeta_abundance$Sample.1,
y=polychaeta_abundance$Sample.2,
shannon.base = 2,
alternative = "greater")
```


